init:
	mkdir -p cancer
	mkdir -p iris
	mkdir -p adult

get_adult:
	cd adult; 
	wget https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data;
	wget https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.test;
	cd - 
